language: node_js
node_js:
- '5.0'
- '4.2'
- '4.1'
- '4.0'
script:
- npm test
after_success:
- ./script/publish_docs.sh
env:
  global:
    secure: wOJz4HNh4LU1jxY5KUOALibwxVSl2dr8JMAUjyE/cfEbI1Xf3C47Vjj53BXFOvELeM167zGhP5tJEUezY2dQtJo55FiDVkj/VIniz6K6TDOdJn6ySCUNz6mIbQ5ClOvNRFw0PLVzuSwssPHln3b8g9BMKlTvPekS4k3cciBeG6G9GtJlATcIZZDx8wjxglxDFSrcgYJyPnDF7jXjrTFQblJMR70O9IXR3mHHR9ym7v9ZGjkJsKmtah4sixJ6dbSLArSwauNHDsK4NpyEEs+RPbSy2IGUy1aH7a9IvpJM49ZElrWcBO2sIYpzlitUAkmh3dMTV/tul0O7b3X7NKW8USUawM6ar4RbagWozgSrtBMTpJR6RTffW+eGz914USnbN3jJXRVD3Pfsxb+MBrVb6hOYoICjE5m0FYnye9FTDDjPgtlw5BDcHmC0oHx/JGo3OH9/VMu/T350yL0ejDzGpD0LS07xrslbVuhbJIFzrQCxAlwo8vbKaX3RaWvcaSHDbUhddW/+Myus2tmjPMZz3wnLZO2r2/KI34wNqdI0HKUdXH3xyDGbSbjDeRDgIP94UphjBqnOeM8fZ9s8dgJigLCu+5NhOaXcWp7vjKm4cHbjn1/gfkoj5k1bsELcItcmf504dKxv3OLx+AiuEtpKPPLWvzsdONzcUrJiSl7o1OU=
